# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff1d5c8da57c3302219b3d34d982d06490616239381efd4d21020effaa38c10bcf8d07260f2168c3a7073af9f7981f8fa839862e7aab76247fe90225a2c9b5e5

test:
  secret_key_base: e6cff88d3f175d2c7f5bc8207d59296f6ebe51c6cc9269761237241c9f9d3e477184e07d1ba071527a8ae9ff79e598fc8994be37178a3839d277d475c51d3e3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
